#
# Copyright 2011  Antonio Franchi and Martin Riedel    
#
# This file is part of TeleKyb.
#
# TeleKyb is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TeleKyb is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with TeleKyb. If not, see <http://www.gnu.org/licenses/>.

# Services will return the Type and relative OptionName within the
# ROS Tree
#
# Service is announced at /TeleKyb/${PACKAGE}_${ID}/options/GetOptionMapping
#
# Options are registered at the Parameter Server at:
# /TeleKyb/${PACKAGE}_${ID}/options/${CategoryName}/${Optionname}
#
# Types are defined by the following ENUM: OVT_UNDEF and NUM_OVT should not occur!
#
# enum OptionValueType {
#	OVT_UNDEF,
#	OVT_DECIMAL,
#	OVT_POSITION,
#	OVT_POSITION3D,
#	OVT_POSE,
#	OVT_STRING,
#	OVT_INT,
#	OVT_BOOL,
#	NUM_OVT
# };

---
uint32[] types
string[] names
