#
# Copyright 2011  Antonio Franchi and Martin Riedel    
#
# This file is part of TeleKyb.
#
# TeleKyb is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TeleKyb is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with TeleKyb. If not, see <http://www.gnu.org/licenses/>.

# Service to receive a String to a running ROS Node.
# Mostly used to receive YAML Definitions to ROSOptions.

---
string output
